plugins:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
    config:
      python_version: 2
  rubocop:
    enabled: true
  reek:
    enabled: true
  eslint:
    enabled: true
  markdownlint:
    enabled: true

exclude_patterns:
- "tests/**"
- "polichombr/static/*.js"
- "polichombr/static/*.css"
