sudo: false

addons:
  apt:
    packages:
      - ruby
      - libffi-dev
      - python-dev
      - graphviz
      - gcc
      - libssl-dev

language: python

python:
  - 2.7

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codeclimate-test-reporter

before_script:
  - python utils/db_create.py

after_success:
  - codeclimate-test-reporter

script: coverage run --omit flask/* -m unittest discover tests/
